#!/bin/sh

currentBranch=$(git current-branch)

read -p "Are you sure you want to delete ${currentBranch}? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

lg -g "Checking out master..."
git checkout master
lg -g "Force deleting (local) branch $currentBranch..."
git branch -D "$currentBranch"
lg -g "Deleting (remote) branch origin/$currentBranch..."
git push origin --delete "$currentBranch"
