#!/bin/sh

currentBranch=$(git current-branch)

read -p "Are you sure you want to delete ${currentBranch}? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

git checkout master
git branch -D "$currentBranch"
git push origin --delete "$currentBranch"
