#!/bin/sh

newCommit=$*

if undefined -s "$newCommit"; then
	lg -g "Name of new commit: "
	read -r newCommit
fi

newCommit="WIP: ${newCommit}"

lgln -g "Unstaging all changes..."
git reset
lgln -g "Committing empty commit with commit name ${newCommit}..."
git commit --allow-empty -m "$newCommit"
lgln -g "Pushing..."
git push
