#!/usr/bin/env zsh

zparseopts -D -E -A args -- s -silent

(( silent = ${+args[-s]} + ${+args[--silent]} ))

git remote -v | grep upstream >/dev/null 2>&1
if [ "$?" -eq "1" ]; then
	if [ $silent = 0 ]; then
	  lgln -r "Not a fork!"
	fi
  false
else
	if [ $silent = 0 ]; then
	  lgln -g "Is fork!"
	fi
	true
fi
