#!/bin/bash

currentBranch=$(git current-branch)

if git diff-index --quiet HEAD -- >/dev/null 2>&1 && git ls-files -o --directory --exclude-standard | sed q | wc -l >/dev/null 2>&1; then
  lgln -g "${currentBranch} is clean!"
  false
else
  lgln -r "${currentBranch} is dirty!"
  true
fi
