#!/usr/bin/env zsh

zparseopts -D -E -A args -- s -silent

(( silent = ${+args[-s]} + ${+args[--silent]} ))

git rev-parse --verify "$*" >/dev/null 2>&1
if [ "$?" -eq "0" ]; then
	if [ $silent = 0 ]; then
    lgln -g "$* exists!"
	fi
	true
else
	if [ $silent = 0 ]; then
    lgln -r "$* does NOT exist!"
	fi
	false
fi

