#!/usr/bin/env zsh

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # no color

zparseopts -D -E -A Args -- g r

if (( ${+Args[-g]} )); then
	color=$GREEN
fi
if (( ${+Args[-r]} )); then
	color=$RED
fi
if [ "$#@" -gt 0 ]; then
	if [[ -z "$color" ]]; then # if color undefined
		color=$GREEN
	fi
	input=$@
fi

echo "${color}${input}${NC}"