#!/usr/bin/env zsh

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'

NC='\033[0m' # no color

zparseopts -D -E -A Args -- g r y

if (( ${+Args[-g]} )); then
	textColor=$GREEN
fi

if (( ${+Args[-r]} )); then
	textColor=$RED
fi

if (( ${+Args[-y]} )); then
	textColor=$YELLOW
fi

if [ "$#@" -gt 0 ]; then
	if undefined -s "$textColor" ; then # if textColor undefined, default to green
		textColor=$GREEN
	fi
	input="$*"
fi

echo "${textColor}${input}${NC}"