#!/usr/bin/env zsh

zparseopts -D -E -A args -- s -silent

(( silent = ${+args[-s]} + ${+args[--silent]} ))

if [ "$#@" -gt 0 ]; then
	if [[ $silent == 0 ]]; then
		lgln -g "Defined!"
	fi
	false
else
	if [[ $silent == 0 ]]; then
		lgln -r "Undefined!"
	fi
	true
fi
